In [1]:
import tensorflow as tf

In [2]:
x = tf.Variable(2.)
w = tf.Variable(3.)
b = tf.Variable(1.)
y_true = tf.Variable(4.)

In [3]:
x

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=2.0>

In [4]:
with tf.GradientTape(persistent=True) as tape:# persistent allows us to call gradient on tape multiple times ...
    y = x * w + b
    loss = abs(y_true - y)

In [6]:
y

<tf.Tensor: shape=(), dtype=float32, numpy=7.0>

In [7]:
loss

<tf.Tensor: shape=(), dtype=float32, numpy=3.0>

In [8]:
tape.gradient(loss, w)

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

In [9]:
tape.gradient(loss, b)

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [13]:
with tf.GradientTape() as tape:
    y = x * w + b
    loss = abs(y_true - y)
tape.gradient(loss, [w, b]) # get the grads of multiple variables without persistent tape

[<tf.Tensor: shape=(), dtype=float32, numpy=2.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=1.0>]